# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
permissions:
  contents: write
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.401

    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
        
    - name: Publish .NET Core Project
      run: dotnet publish testgithubpages.csproj -c Release -o release --nologo # -p:GHPages=true

    - name: prerender Blazor client
      working-directory: release/wwwroot
      run: npx react-snap
      
    - name: Change base tag
      working-directory: release
      run: |
        find . -name "*.html" | while read htmlFile; do
            sed -i 's/<base href="\/"/<base href="\/testgithubpages\/"/g' $htmlFile
            sed -i 's/<script type="text\/javascript">var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;<\/script><script src="_framework\/dotnet.7.0.12.js" defer="" crossorigin="anonymous"><\/script>//g' $htmlFile # integrity="sha256-SWZOE2EsCqc\/7dPgJrcFqUvVvdeJ9cipeZ2NFMC9v2s="
        done

    #- name: Change base-tag in index.html from / to testgithubpages
     # run: sed -i 's/<base href="\/" \/>/<base href="\/testgithubpages\/" \/>/g' release/wwwroot/index.html
      
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
        force_orphan: true